# Build the application first using Maven
FROM maven:3.8-openjdk-17 as build
WORKDIR /app
COPY . .
RUN mvn clean install

# Inject the JAR file into a new container to keep the file small
FROM openjdk:17-jre-slim
WORKDIR /app
COPY --from=build /app/target/aws_demo-*.jar /app/app.jar
EXPOSE 8080
ENTRYPOINT ["sh", "-c"]
CMD ["java -jar app.jar"]